version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres-local
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: UserDB
    ports:
      - "5434:5432"