server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # R2DBC - используется для работы с Postgres
  r2dbc:
    url: r2dbc:postgresql://${PSQL_DATASOURCE_URL:localhost}:5434/UserDB
    username: ${PSQL_DATASOURCE_USERNAME:postgres}
    password: ${PSQL_DATASOURCE_PASSWORD:postgres}

  # JDBC - используется для Liquibase
  liquibase:
    enabled: true
    change-log: db.migration/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5434/UserDB
    user: postgres
    password: postgres

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1 # Параметр ПОДТВЕРЖДЕНИЯ получения брокером сообщения от продюсера
        delivery.timeout.ms: 10000
        linger.ms: 0
        request.timeout.ms: 5000
        enable.idempotence: false # Параметр для обеспечения ИДЕМПОТЕНСТНОСТИ направления сообщения в брокер
        max.in.flight.requests.per.connection: 5

    consumer:
      group-id: user-created-events # Консьюмер ГРУППА
      properties:
        spring.json.trusted.packages: "com.aston.userservice.event"

jwt:
  secret: ${JWT_SECRET_KEY:357638792F423F4428472B4B6250655368566D597133743677397A2443264629} # Секрет для генерации JWT токена пользователю