server:
  port: 8082

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://${PSQL_DATASOURCE_URL:localhost}:5434/UserDB
    username: ${PSQL_DATASOURCE_USERNAME:postgres}
    password: ${PSQL_DATASOURCE_PASSWORD:postgres}

  liquibase:
    change-log: db.migration/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all # Параметр ПОДТВЕРЖДЕНИЯ получения брокером сообщения от продюсера
        delivery.timeout.ms: 10000
        linger.ms: 10
        request.timeout.ms: 5000
        enable.idempotence: true # Параметр для обеспечения ИДЕМПОТЕНСТНОСТИ направления сообщения в брокер
        max.in.flight.requests.per.connection: 5

    consumer:
      group-id: user-created-events # Консьюмер ГРУППА
      #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.aston.userservice.event"

  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/UserMNG?authSource=admin

jwt:
  secret: ${JWT_SECRET_KEY:357638792F423F4428472B4B6250655368566D597133743677397A2443264629} # Секрет для генерации JWT токена пользователю