server:
  port: 8082

spring:
  jpa:
    show-sql: true

  datasource:
    url: jdbc:postgresql://${PSQL_DATASOURCE_URL:localhost}:5434/UserDB
    username: ${PSQL_DATASOURCE_USERNAME:postgres}
    password: ${PSQL_DATASOURCE_PASSWORD:postgres}

  liquibase:
    change-log: db.migration/db.changelog-master.xml

  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer